# Generated by Django 3.2.7 on 2021-09-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=10000, unique=True)),
                ('short_url', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
